### ISSUE TITLE
transclusion with ng-forward

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#44]
How may i migrate a directive with transclusion?
Will ng-forward support the content tag like in angular2?
If not what will be the preferred solution?

**Comment by MikeRyan52** [comment]
We're going to follow the same path as Angular 1.5's new component helper and turn on transclusion by default for all components. This is OK because in Angular 1.5 transcluded content is not even parsed until the transclude function is called on it.

It should also be noted that we do not plan on supporting a content tag. Instead, use the ng-transclude directive as an element to make swapping it out for a content tag easy.

Transclusion by default will land in our next release. Until then, feel free to use the internal `@Transclude` decorator on your component.

**Comment by david-gang** [comment]
thanks

**Comment by david-gang** [comment]
Hi @MikeRyan52 .
I think it would be helpful to have a remark on this in the documentation.
I am sure i won't be the only person who asks this
