### ISSUE TITLE
problems with ngsanitize and (click) attribute

### ISSUE THREAD

**Issue by david-gang** [ngUpgraders/ng-forward#54]
Hi,

I don't know if this is a problem with angular sanitize or ng-forward but it does not recognize the (click) attribute.

I renamed ng-click="" to (click)=

I get 

Error: Failed to execute 'setAttribute' on 'Element': '(click)' is not a valid attribute name.
    at Error (native)
    at forEach.attr 
    at Object.JQLite.(anonymous function) [as attr] 
    at Object.$$sanitizeUriProvider.$get.Attributes.$set 
    at http://localhost:8000/primo-explore/lib/bundle.js:52302:15
    at forEach 
    at mergeTemplateAttributes 
    at applyDirectivesToNode 
    at compileNodes 
    at compileNodes 

I am using angular-sanitize 1.4.7

Please let me know if i should continue this here or open a defect to angular-sanitize.

Thanks,
David

**Comment by timkindberg** [comment]
@petebacondarwin this bug seems a bit crazy. Can you send this over to a sanitize expert and see if our special attributes seem like they might cause a problem?

**Comment by petebacondarwin** [comment]
I will take a look

**Comment by petebacondarwin** [comment]
@david-gang - can you provide some more information?
Ideally could you create, a live code example, perhaps on Plunker, that demonstrates this issue?
Also if you could indicate the browser as well?
Cheers
Pete

**Comment by david-gang** [comment]
Hi @petebacondarwin 
I managed to setup a plunkr.
I can just reproduce it with md-button of angular-material, not with the native html elements

http://plnkr.co/edit/ieSrnKOd5i5OUP3NAUO9?p=preview

**Comment by petebacondarwin** [comment]
OK, so this is a pain. It seems that we cannot use `element.setAttribute()` with attribute names that start with `(`. See http://plnkr.co/edit/3aaZg6ADJ9DDMUZqK3kE?p=preview

**Comment by petebacondarwin** [comment]
Let's see what they do in Angular 2 ...

**Comment by petebacondarwin** [comment]
See https://github.com/angular/angular/issues/133

**Comment by david-gang** [comment]
Hi @petebacondarwin . I tried to go over the whole thread. Do you see there a bottom line, aside that this issue is closed?  :-)

**Comment by petebacondarwin** [comment]
The bottom line, regarding browsers is that they will parse the syntax as HTML but not allow you to programmatically write to it.

I believe is that Angular 2 avoids ever writing to DOM attributes. If you remember, in Angular 2 the `()` and `[]` syntax refers to properties on the underlying DOM object (or in the case of components the component instance). This means that although they use the syntax in the HTML they never need to call `setAttribute` with an "invalid" attribute name.

I am not sure how we can get around this in Angular 1 and ng-forward.

There is, though, alternative syntax in Angular 2, which uses `bind-...` and so on instead of this "invalid" shorthand. We may have to go with that instead, if we can't find a solution.

**Comment by MikeRyan52** [comment]
We could feasibly generate two sets of directives for events, one supporting `on-${event}` and another supporting `(${event})`, however with properties it would be best if we picked just one syntax. Thoughts @timkindberg ?

**Comment by david-gang** [comment]
Hello @MikeRyan52 
Would it be possible that we will use (click) attributes in the template but behind the scenes it will be converted to bind-click ?

**Comment by timkindberg** [comment]
@MikeRyan52 I'd kind of thought of doing that, but I remember you preferring to choose one. I do wonder sometimes what level of template parsing we might be able to do. A quick regex over the template string might not hurt, converting bind-* to [*]. I'm trying to think of the dangers in doing that.

**Comment by timkindberg** [comment]
ugh... I keep avoiding this issue. @petebacondarwin so give it to me straight. Do we have to ditch the special bind syntax?

**Comment by petebacondarwin** [comment]
Let me have a think about it today

**Comment by petebacondarwin** [comment]
Didn't get to it today. Over the weekend, I promise.

**Comment by petebacondarwin** [comment]
So, I think, the good news is that this is only a problem, I think, if the directive uses `replace: true`, such as the `md-button` directive from Angular Material, I think.
Since we have deprecated this and generally discourage its use we might be able to get away with saying that you cannot use `(...)` style attributes on elements that contain directives that use replace.

**Comment by david-gang** [comment]
Nice. I also like this approach. I'll contact the material team :-)

**Comment by petebacondarwin** [comment]
I spoke with @IgorMinar about this and I am going to patch Angular so that it can handle this situation. There are too many potential directives out there that could break due to this.

**Comment by timkindberg** [comment]
Good news!

**Comment by david-gang** [comment]
Hi @petebacondarwin 
May you please reference an issue from angularjs where i can track this issue and when it was fixed?

Thanks in advance,
David

**Comment by petebacondarwin** [comment]
Done: https://github.com/angular/angular.js/issues/13317

**Comment by petebacondarwin** [comment]
@david-gang : https://github.com/angular/angular.js/issues/13317 has landed.

**Comment by david-gang** [comment]
@petebacondarwin thanks for the super fast fix
